// Generated by https://quicktype.io

export interface PokemonList {
  count:    number;
  next:     string;
  previous: null;
  results:  Pokemon[];
}

interface Pokemon {
  name: string;
  url:  string;
}
